CREATE TABLE tovGroups(
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(50),
  Rahunok INTEGER DEFAULT NULL,
  INDEX USING BTREE (`Rahunok`)
)
ENGINE=MyISAM;

INSERT INTO tovGroups (id, name) VALUES (1,'Загальна');

CREATE TABLE tovPerelik(
  id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  GroupID INTEGER DEFAULT 0,
  Nomer VARCHAR(20) DEFAULT NULL,
  Name VARCHAR(150) DEFAULT NULL,
  Odynyci VARCHAR(10),
  Cina DOUBLE(16,6),
  Cina_1 DOUBLE(16,6),
  Cina_2 DOUBLE(16,6),
  Cina_3 DOUBLE(16,6),
  ForPrice BOOLEAN DEFAULT false,
  Prymitka VARCHAR(50),
  INDEX USING BTREE (`GroupID`, `Nomer`)
)
ENGINE=MyISAM;

CREATE TABLE nakladnaVh(
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Num VARCHAR(10) DEFAULT NULL,
	CDate DATE DEFAULT NULL,
	Partner_id INT DEFAULT NULL,
	Prymitka VARCHAR(50) DEFAULT NULL,
	INDEX USING BTREE (`Num`, `CDate`, `Partner_id`)
)
ENGINE=MyISAM;

INSERT INTO nakladnaVh (id, Num, CDate, Partner_id, Prymitka) VALUES (1, '0001', CURDATE(), 1, 'Вхідні залишки');

CREATE TABLE nakladnaVyh(
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Num VARCHAR(10) DEFAULT NULL,
	CDate DATE DEFAULT NULL,
	Partner_id INT DEFAULT NULL,
	Prymitka VARCHAR(50) DEFAULT NULL,
	INDEX USING BTREE (`Num`, `CDate`, `Partner_id`)
)
ENGINE=MyISAM;

CREATE TABLE skladPakety(
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	TovOrder SMALLINT DEFAULT NULL,
	NakladnaVh_id INT DEFAULT NULL,
	Tovar_id INT DEFAULT NULL,
	Kilkist DOUBLE(16,6) DEFAULT NULL,
	Cina DOUBLE(16,6) DEFAULT NULL,
	Closed BOOLEAN DEFAULT FALSE,
	INDEX USING BTREE (`TovOrder`, `NakladnaVh_id`, `Tovar_id`, `Kilkist`, `Closed`)
)
ENGINE=MyISAM;

CREATE TABLE vidpuskTovariv(
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	TovOrder SMALLINT DEFAULT NULL,
	NakladnaVyh_id INT DEFAULT NULL,
	Paket_id INT UNSIGNED DEFAULT NULL,
	Kilkist DOUBLE(16,6) DEFAULT NULL,
	Cina DOUBLE(16,6) DEFAULT NULL,
	Closed BOOLEAN DEFAULT FALSE,
	INDEX USING BTREE (`TovOrder`, `NakladnaVyh_id`, `Paket_id`, `Kilkist`, `Closed`)
)
ENGINE=MyISAM;

CREATE TABLE dovPartners(
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Name VARCHAR(100) DEFAULT NULL,
	EDRPOU VARCHAR(12) DEFAULT NULL,
	Adresa VARCHAR(100) DEFAULT NULL,
	Tel VARCHAR(30) DEFAULT NULL,
	PlatnPdv BOOLEAN DEFAULT false,
	IPN VARCHAR(12) DEFAULT NULL,
	SvidPdvNum VARCHAR(10) DEFAULT NULL,
	UgodaNum VARCHAR(20) DEFAULT NULL,
	UgodaDate DATE DEFAULT NULL,
	Prymitka VARCHAR(100) DEFAULT NULL,
	IsKlient BOOLEAN DEFAULT FALSE,
	IsPostach BOOLEAN DEFAULT FALSE,
	INDEX USING BTREE (`IsKlient`, `IsPostach`, `PlatnPdv`)
)
ENGINE=MyISAM;

INSERT INTO dovPartners (Name, IsKlient, IsPostach) VALUES ('Наше підприємство', true, true);

CREATE TABLE IF NOT EXISTS `orgInfo` (
   `id` INT(4) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	PidprId int,
	PovnaNazvaPidpr VARCHAR(100) NULL,
	ScorochNazvaPidpr VARCHAR(80) NULL,
	Edrpoy VARCHAR(8) NULL,
	Adresa VARCHAR(90) NULL,
	Fax VARCHAR(20) NULL,
	Email VARCHAR(50) NULL,
	PipDurect VARCHAR(50) NULL,
	PipBuh VARCHAR(50) NULL,
	TelefonDurekt VARCHAR(20) NULL,
	TelefonBuh VARCHAR(20) NULL,
	Bank VARCHAR(150) NULL,
	MFO VARCHAR(8) NULL,
	BankRahunok VARCHAR(14) NULL,
	Podatok TINYINT DEFAULT 0,
	PodatokVal DOUBLE(5,2) DEFAULT 0,
	IPN VARCHAR(12) NULL,
	SvidPDVNum VARCHAR(10) NULL,
	CinaZPodatkom BOOLEAN DEFAULT true
)
ENGINE = MyISAM;
INSERT INTO `orgInfo` (PidprId) VALUES (1);

CREATE TABLE IF NOT EXISTS `vydyOplaty` (
   `id` INT(2) NOT NULL PRIMARY KEY AUTO_INCREMENT,
   `Name` VARCHAR(20) NULL
)
ENGINE = MyISAM;
INSERT INTO `vydyOplaty` (id, Name) VALUES 
(1, 'Готівка'),
(2, 'Перерахунок'),
(3, 'Бартер'),
(4, 'Рішення суду'),
(5, 'Взаємозалік');

CREATE TABLE IF NOT EXISTS skladDbVersion(
 id INTEGER UNSIGNED,
 ver INTEGER UNSIGNED
);

INSERT INTO skladDbVersion(id, ver) VALUES (1,1);